coverage:
  precision: 1
  round: down
  status:
    project:
      default:
        target: 90%
        threshold: 0%
    patch:
      default:
        target: 90%
        threshold: 0%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

github_checks:
  annotations: true
